export default {
  USER_LOGOUT: 'REACT_USER_LOGOUT', //                                               user logout
  USER_SING_UP: 'REACT_USER_SING_UP', //                                             user sign up
  USER_SING_IN: 'REACT_USER_SING_IN', //                                             user sign in
  USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE', //                                     update user profile
  USER_ERROR: 'REACT_USER_ERROR', //                                                 user sign in
  USER_CONFIG_MUSIC_STYLE: 'REACT_USER_CONFIG_MUSIC_STYLE', //
  USER_CONFIG_I_AM_A: 'REACT_USER_CONFIG_I_AM_A', //
  USER_FAVORITES: 'REACT_USER_FAVORITES', //
  USER_INFO: 'USER_INFO', //

  VIDEO_LIST: 'VIDEO_LIST',
  ALBUM_LIST: 'ALBUM_LIST',

  SOURCE_DELETE_ALBUM: 'SOURCE_DELETE_ALBUM',
  SOURCE_DELETE_VIDEO: 'SOURCE_DELETE_VIDEO',

  HOME_USER_LIST: 'HOME_USER_LIST',
  HOME_USER_LIST_DETAIL: 'HOME_USER_LIST_DETAIL',

  I_WANT_YOU_DELETE: 'I_WANT_YOU_DELETE',
  I_WANT_YOU: 'I_WANT_YOU',
  FAVORITES_MINE: 'FAVORITES_MINE',

  HOME_PERSON_DETAIL: 'HOME_PERSON_DETAIL',
  MAP_SERACH_ADDRESS: 'MAP_SERACH_ADDRESS',
  MAP_REVERSE_GPS_GET_ADDRESS: 'MAP_REVERSE_GPS_GET_ADDRESS',

  COMMENT_GET_LIST: 'COMMENT_GET_LIST',
  COMMENT_DELETE: 'COMMENT_DELETE',
  COMMENT_ADD: 'COMMENT_ADD',
  COMMENT_REPLY: 'COMMENT_REPLY',

  CHAT_USER_MSG_MAP: 'CHAT_USER_MSG_MAP',
  HOME_CAROUSEL: 'HOME_CAROUSEL',
};
